name: Deploy Infrastructure
on:
  workflow_call:
    inputs:
      work-dir:
        required: true
        type: string
      aws-region:
        required: true
        type: string
    secrets:
      CI_ROLE:
        required: true
      TERRA_PRIVATE:
        required: true

jobs:
  Infra-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.work-dir }}
    steps:
      - name: AWS Creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.CI_ROLE }}
          aws-region: ${{ inputs.aws-region }}

      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform format
        run: terraform fmt -check
      - name: init
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< '${{ secrets.TERRA_PRIVATE }}'
          terraform init
      - name: Validate
        run: terraform validate
      - name: Plan
        run: terraform plan
     # - name: Apply
       # run: terraform apply -auto-approve