name: s3 Deploy
on:
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write
  statuses: write
  actions: read
  contents: read

jobs:
  call-s3-workflow:
    uses: ./.github/workflows/deploy.yaml
    with:
      work-dir: "environments/s3"
      aws-region: "us-east-2"
    secrets:
      CI_ROLE: ${{ secrets.CI_ROLE }}
      TERRA_PRIVATE: ${{ secrets.TERRA_PRIVATE }}